spring:
  application:
    name: core
  jackson:
    serialization:
      write-date-keys-as-timestamps: false
    date-time-format: ${JACKSON_SERIALIZATION_DATE_TIME_FORMAT}
  main:
    allow-circular-references: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    password: ${MAIL_PASSWORD}
    username: ${MAIL_USERNAME}
    properties:
      mail:
        smtp:
          auth: ${MAIL_PROPERTIES_SMTP_AUTH}
          starttls:
            enable: ${MAIL_PROPERTIES_SMTP_STARTTLS_ENABLE}
  quartz:
    job-store-type: ${QUARTZ_JOB_STORE_TYPE}
    jdbc:
      initialize-schema: ${QUARTZ_JDBC_INITIALIZE_SCHEMA}
    properties:
      org.quartz.jobStore.driverDelegateClass: ${QUARTZ_PROPERTIES_ORG_QUARTZ_JOBSTORE_DRIVERDELEGATECLASS}
      org.quartz.scheduler.instanceId: ${QUARTZ_PROPERTIES_ORG_QUARTZ_SCHEDULER_INSTANCEID}
      org.quartz.threadPool.threadCount: ${QUARTZ_PROPERTIES_ORG_QUARTZ_THREADPOOL_THREADCOUNT}

environment:
  dateTime:
    distance: ${DATETIME_DISTANCE}
    unit: ${DATETIME_UNIT}
  date:
    distance: ${DATE_DISTANCE}
  accessToken:
    secretKey: ${ACCESS_TOKEN_SECRET_KEY}
    expired: ${ACCESS_TOKEN_EXPIRED}
  refreshToken:
    expired: ${REFRESH_TOKEN_EXPIRED}
  map:
    apiKey: ${MAP_KEY}
    goongDomain: ${MAP_DOMAIN}
    reverseGeo: ${REVERSE_GEO}
    detail: ${ADDRESS_DETAIL}
    place: ${PLACE}
  aes:
    secretKey: ${AES_SECRET}
  payOs:
    api-merchant-host: ${API_MERCHANT_HOST}
    client-id: ${CLIENT_ID}
    api-key: ${API_KEY}
    checksum-key: ${API_CHECKSUM_KEY}
    returnUrl: ${RETURN_URL}
    cancelUrl: ${CANCEL_URL}
  commission:
    percent: ${COMMISSION_PERCENT}