spring:
  application:
    name: core
  jackson:
    serialization:
      write-date-keys-as-timestamps: false
    date-time-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/net_pool_station
    username: root
    password: minhtranquang2197
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    password: kqwb ipyc gkeh ligm
    username: brokenstar2197@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  quartz:
    job-store-type: memory


    properties:
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.threadPool.threadCount: 10
  profiles:
    active: develop

server:
  port: 8080

environment:
  dateTime:
    distance: 1
    unit: DAY
  date:
    distance: 7
  accessToken:
    secretKey: ftoLRVxHq82BzLq3stXhnOJRo4azrVab
    expired: 900000
  refreshToken:
    expired: 7
  map:
    apiKey: gMs7uHEjx646z9dVVjrh60fRPMADssbjc2Z7KYd1
    goongDomain: https://rsapi.goong.io
    reverseGeo: /Geocode?api_key=${environment.map.apiKey}
    detail: /geocode?api_key=${environment.map.apiKey}
    place: /Place/AutoComplete?api_key=${environment.map.apiKey}
    placeDetail: /Place/Detail?api_key=${environment.map.apiKey}
  aes:
    secretKey: xIsKmo2DjotZyB6TrM323CjHCd4HLKt1D0f0PVlVfEnmFChtoboeSktF2GKUcSIMYNX5HdQeKbtpWLHN4qbGWQvuOATq20YCfygyLbKqZrxzvgKd73B4yJsTnmujuujaTkVqEA8nLQkPgKgZIWWpDMG8buXdlcHD1hDyJAe0ttxqaBI1OKOnpIG8GyprJY6cxNiHjPkQ3myye3G0nkQtJ4LmIvRtMm9uGo6cqKwvKqLTGv8ttBmCm0LaQ76h7SbwW6cwAQGHdmeyiI2KSWUvO1b5SY3fB5erlxUDl4ohlfFHQvmfiLkoNONov0Pi2BHKoRRXRUjLVQucaZLbOfbuYOpGKbBmc2DwSJiNkaTDpBgISV3Sf2NQCyd3inZbKpOc03WTG6Zz9UyRt1e2D01vKwB7vs90RCDVMlTIo8IXIdNXaegwLQt1r6oecqrkklJ2Ujne23wZLFVDgm8iENuLI5IMj3abUGnFhBx3YwrTyL8LTiHWqFSRlX6yLEh35n5BtqizfrfZbwpIKLso8bfyRV33Xaz6lN7rhQSQiZatxNWdytKAn0w1tdAEKpGU4pWEguqZSDz0rn0Nos6B3bWQG3Ktag9JzWFO99WCfvs5UVBD875bOYLAlJfZd6iDb3YcDVzyli6XdhhEcjnbtYjKNQTpzt9FGXpO3ZVnXfMkQe6410wbPl2zYcMIbPqNS1o6qev3qlGNffOiUOTclWxE9EJDmQSTz8Q7TiKO4te8fEMZLbXe4NmYiDcg6eHNZForh945BBcVjh8wOqMIA1IEFxnMUTUUQ2bD8HEg5HlEDfmmKzUXgR484BvZlwS3eRgWNuaOFOQTiPI2LHQxRK8Emu8lQ7lqRaZmMyeubA7JwK8MXiG7VnIf98kf2Z1LUb8eB5XTJMCUGBI92vWDvf0m8GzbyzWB6vys0KdpGBQvfM2iwKQYvZ8jnYavo2iTRhez1G2fkXFnR7HXOO6USXhKLqbwg8tYKQYEsCGKOjZBhpMDugQg27w5DL1uRHuYhBUcllbhw191vRqozOVnxHQJsHWeqoDKY7tThdkuU79D56wc6eauIpVOdQ3dmkVADGYaw5WaEXOkQp7aATYYGeSyHLj77Fx9DMEmzc9e3pnB8tFt2oeWEvU5rVYze4nHYSw2oj6EmdA4nrlmR7gMn5STXsga029oOyVO0nCtaRf3EGF7ZOYB8sfHSju3Brh7XhtPq5ypruOLeHJp6CCitN1PkdclHtP6fhH7Y3jufuVOepgf40O3lHsVXqRBUHBe80jJ1H7dDMNEZMgFTvSoDDpBF3TGJyWtxmBi7QjpwEJxI23JvNS6pqoqRJFPjOsvnL8B2UOuMv2PCnyYsRbafCCJdF2R2YADDuJC51EqySuy27Km7L2ibu9P38O9mbTlXnHYLVKVNqtGfxSpzQCCKrqUsLdvVPsIatDS0DYKoxZ4oy1p1qQR4MAtnLz7m7nc32Z8tiMOyKsMr8mEwvMv7uk5dyCYSXIwyzh5RUwbseXuTF66mVoPa6NsMiQ7qMEsj4rvb0X5PEtz0IgzcmN9B3O31mxhx3WdLUJs5D1QlujZLTzyrnYVC4ouKXY7HXGf7kojGJGXpPhwSXacYt1P3RWj5m5zniZAmUTOMuywNFXPronvaPxnHjKMsrXwOgX5uEvQFDUVqODhcHfg407hGCiYiAB2yTS8ANA3MPtHfnnyDS6hWrXDpKKlpv2QK5qa2n9kefVUGz5xOGuGCvtlDVcQ0J1vAzF3tSpObl8Qy1TMP0LhbCxXhnf8PaOLuVUuX0XYCt1WhmGiscwSG6QgJ11WzasgOKb5670ra0ZDDJERxhzvUsi4yjtjKwxrtk0BwFLXDCwSscnSXjC0XhmAXP4oRyhKMNvX3ps86pMow5ipnokipi8bWmCDJAhe4M2bkTJ6DEjUy7zrT5JVc6yPFcE6qVo7MzWndhLbL71OJmu5Gopus5jRHn9ddnXVVnVN7Yzg3idN2DK2zbQYdFPL9bGqHgm8C1wPB3OGSHyFlF17cogRAwckoMOHBEH8WGGVniaEHGVgtbAX21UD5FYEtxoNTfiKBOnP2nHiCNHxClWvt2Uw16bdQOxbmDdFdb2QVLsgMzobTwmGJXFAF8gg31Ii7eIBGluUNBcLDZSNZId4QnrkpctVnGh7DEH3Cf7VKLAyTZAlquSWAM1CTIBBwBN8YoG2jFu25r4sdjI3ID5qUDXKTEiK2Y6MhqKTUGNHIl16SnG3JvU0ahxdMxD9HBUSTaD6E6UHDSy9mBlcA1CZFZ2L93RcZCyS08bny7IOKzob0tafjetiZcUyfR1EiMeVLlpddDvfB4D0TfSm8Bs9YRBO8n18XXD83oVnCuJN797HhsnQCBWPECToVsxp7NWU5wkhmDvwY13TD8t35bHU0GlSmMnjjxyaFyXRpNgyi8K4unaaDq66DrLdjPkUBCaXGnDE07G10G3q712mx2MajmIdeq4odBpypIdcOxTISasPVyhBZmCm6PnK2aO6eFBYkUuvedNmLnKRwayGffd9mchZmWY2dWw3tWCBtCgOHgwotfB4qimQ6IsDUlFOzDdsYJ55XZN6asZJ0IMyp7qHODnokagCErVphsuRxBcPLIEvbWuV2RcW8GReaf4Fac5SHGawG230p1lBcTokqz8A0pmEe1MSpenz6r9bQ6fmYHZVBfJoK6wMBr7cC0tCq6QdFQOCWjAz8zrP8HqP2kI6ZmnH6ehf1CtXgY3vqYq7vqgJskH0pgEj23LYdk6iqavk043m6S6zB1t3m07ig4RIfpuuxmtIwyPRiqpeCkOUJScmhLCff2qEehqtOFc5mUKqfsilTb5HvUabLnMewJ3hFXwbEi27jeo7qBpwolZpNz9u7LZYaLOSwrcOm6Qcjcxnd030a9KvRWA7ahMOniDOydLXFDdwguyAEjwMGmXl8mHZO5et0ri0JE5Y0gdOSdgcpyF8K6DbXFemzEZ6UdlmjHNYCb8IYjIanQ71RHkHT1sPtAwLL5o9iJ0NGWuEZmKVD0eKuox8zC0hLBhUCN0Dy8k068LHZeVNmuqfAiGOya0Qw4QRaJeF4v3jR0Lbqz66MILzuVuonqUFgGmzdR2fPdzhELTsfeSaFmW0kk1An8FgO1XTb2g48qYqCOPSvHxzSpiQlFDPNKl8gY0EppWbmY90kZ4jiT1xOHIRI845wwvoj6LvpPTeWmuYhTMJSqekwipDH5xbWp5KvbMK9HdWO0B7zlrASSj5N6pQLAvkGo18FxqldEQGEAW95ioNl07mbmCOuBlhWxoKZXRGaQnJ86MWwCmu57OvhRefnPnFfwYPeFRHlW4MwS25e6zzv0KRqhSsihNpkgB07dJ870nk3OGqtRd3lILqnhIqvRbzyvOqFN8yCUP5q1lthbLzcGG38FDSt2EF9p74bXb1BMGPXg4KzyDIVMzl4QcfpttAQWTTB5QbxLjCwxkDe47Fwu4xHZM5YEFZhq3eDQH211OBGoxhwS399Rp8lVwLaiRmUiWTTlNhUv5okcMyyrxEIAEpWXOm4nUddfH2nd6uJcrapjrZMvtSXxDbh2V91TRPAwNDckSukK6T9Vd1YManVIKUEOzaqSFaT6IFP90KYRNjSmUgPGxz3uDQyl4HN7cYwGGMLz3zgZcrEBr3k3XoPpBknHa2vRCJcO92PhuY4JmAc0tqtKqbZ61zSbKNl1hm4now4J8BkVntEcQ706SMklAVXANyp8h1baQLD8ne9a3LYlVT3Q3R1BA4JQyGm71zk2mwyOqAiT9jyqU4SMAI9UOvJ2Yy8p45HFejELG4Xgt6JZhnFyj8PuuSFDNjnQaMLFsMfOwLSjsWdqWixuCjp2qiRZnM4BoXWjKn1n8ffTYdgOWdgManHLv10ScSqBS87WMCXo1RsRy0bA8WeSOyPBWfQUaGJvxriuiD4SvgYdayT2KyId77KdjIPGLSi7KDVlYh1sluf07VT3JhVNtFtnAoDw6Sf0v9EYhd
  payOs:
    api-merchant-host: https://api-merchant.payos.vn
    client-id: a6485626-40e8-4cfe-ab80-edb736eaaa54
    api-key: d0e437e6-2399-486d-8539-dc4652a7b489
    checksum-key: 93110692661c057429c7df81b5c3e743831e4d59d1c3113cd2497fd9be8ce107
    returnUrl: http://localhost
    cancelUrl: http://localhost
  commission:
    percent: 5